version: "3.8"

services:
  mysql:
    image: mysql:8.0.41
    container_name: Container_modelagem
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bd-modelagem
      # Se quiser criar um usuário próprio descomete e coloque seu nome e senha
      # MYSQL_USER: Seu-nome-de-usuário-aqui
      # MYSQL_PASSWORD: Sua-senha-aqui
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
